import "./globals.css";
import { Inter } from "next/font/google";
import Header from "./components/common/Header";
import Footer from "./components/common/Footer";
import Provider from "./components/session/Provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Blog App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <Provider>
                    <Header />
                    <main>{children}</main>
                    <Footer />
                </Provider>
            </body>
        </html>
    );
}
